### ISSUE TITLE
Additional datasets to consider

### ISSUE THREAD

**Issue by maglet** [uw-madison-comps/R-lessons#2]
The Iris dataset works for about 90% of the R lessons, but doesn't have: 
1. Multiple categorical variables to group by
2. A time-series component
3. Extra numeric variables for exercises

Here is a list of other datasets to consider: 
1. NEON https://www.neonscience.org/neon-plant-pheno-data-r (complex, would need to spend time to pare it down, but has multiple categorical variables and a time series) 
2. From the datasets package: https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/zCO2.html (multiple categorical variables, no time series)

Feel free to add!

**Comment by SteveGoldstein** [comment]
Two datasets distributed with R:
Orange:  The Orange data frame has 35 rows and 3 columns of records of the growth of orange trees.
trees:      This data set provides measurements of the diameter, height and volume of timber in 31 felled black cherry trees. Note that the diameter (in inches) is erroneously labelled Girth in the data. It is measured at 4 ft 6 in above the ground.

**Comment by SteveGoldstein** [comment]
Kim O'Keefe is preparing an advanced lesson for the third 2 hour session that will have data that can be used in the first two session.  The data have multiple categories for grouping and time series.  She'll come on Monday July 22 and we can decide how to use it.

**Comment by SteveGoldstein** [comment]
Resolved by PR #3 .

Kim's Physiology_Environmental_Data.csv dataset (285 rows, 18 columns).
